// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'codemirror': string;
  'flowTable': string;
  'flowTree': string;
  'graphContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
